### ISSUE TITLE
usleep?

### ISSUE THREAD

**Issue by Jokeren** [lxhq/BRAVOtest#2]
https://github.com/lxhq/BRAVOtest/blob/f370112ddcd36effea5724480e411787bf9d2457/BRAVOLock.c#L82

usleep(1) sleeps for 1000 nano seconds, which could be about 3000 cycles, is it too many?

**Comment by Jokeren** [comment]
There are also other issues. We need to discuss them tomorrow.

**Comment by lxhq** [comment]
Sure. Sorry about that. I will try to find some function that pauses smaller than usleep(1);
